name = "BerghA"
uuid = "f2fac6c4-9609-4442-bbda-8eba9356dd10"
authors = ["Henry Talbott", "Dhruv Bhatia", "Daniel Li", "Dan Abramovich", "Stephen Obinna", "Lars Kastner", "Chen Li", "Nada Benabla"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
